### PR TITLE
drivers/timers/capture: fix typo in capture.h

### LINKED ISSUE #16835: [TYPO] drivers/timers/capture: CAPIOC_FREQUENCE is not standard english
Fixing the typo would require updating:
- drivers/timers/capture.c
- include/nuttx/timers/capture.h

And would be a breaking change. Would need to update the capture example in nuttx-apps for instance.

_Originally posted by @acassis in https://github.com/apache/nuttx/pull/16830#discussion_r2269675106_

### PR DESCRIPTION
**Pull request by comejv**
## Summary

This commit fixes a typo in the capture.h header file (fix #16835).

Change: CAPIOC_FREQUENCE -> CAPIOC_FREQUENCY

Added a compiler warning of the deprecation to the capture.h file.

Updated capture driver and documentation.

## Impact

Now shows a compiler warning when using the capture driver. Old spelling is aliased to the new spelling. Should be removed in future releases. 

## Testing

Built config capture on Ubuntu.

### CODE REVIEW

File: include/nuttx/timers/capture.h [hunk 1]
```diff
@@ -45,14 +45,23 @@
...
  */
 
-#define CAPIOC_FREQUENCE _CAPIOC(2)
+#define CAPIOC_FREQUENCY _CAPIOC(2)
+
+/* Deprecated alias: keep object-like so existing code compiles unchanged */
+#define CAPIOC_FREQUENCE CAPIOC_FREQUENCY
+
+#if defined(__clang__)
+  #pragma clang deprecated("CAPIOC_FREQUENCE", "Use CAPIOC_FREQUENCY; CAPIOC_FREQUENCE will be removed on 2026-01-01")
```
Comment (fdcavalcanti) [inline include/nuttx/timers/capture.h]: Are you the one that is going to remember and remove this on new year's day?

File: include/nuttx/timers/capture.h [hunk 2]
```diff
@@ -45,14 +45,23 @@
...
  *              with the errno value set appropriately.
  */
 
-#define CAPIOC_FREQUENCE _CAPIOC(2)
+#define CAPIOC_FREQUENCY _CAPIOC(2)
+
+/* Deprecated alias: keep object-like so existing code compiles unchanged */
+#define CAPIOC_FREQUENCE CAPIOC_FREQUENCY
+
+#if defined(__clang__)
```
Comment (xiaoxiang781216) [inline include/nuttx/timers/capture.h]: not good to check compiler in the common code

**Comment by raiden00pl** [comment]
Why not just correct the typo without any additional warnings and delete the old define?
This change will cause a compilation error anyway. This is an example of a breaking change that is trivial to fix and immediately visible when migrating to the new NuttX version. In such cases, complicating the process doesn't help at all and makes no sense to me.

**Comment by acassis** [comment]
@comejv just fix like raiden suggested and fix the typo CAPIOC_FREQUENCE. But I think the idea of creating a macro to define a DEPRECATED feature is interesting for later maintenance and to warn users about APIs that will change.

**Comment by linguini1** [comment]
Hey @comejv, if you can update this PR to follow raiden00pl's suggestion it can be merged!

**Comment by acassis** [comment]
ping @comejv

**Comment by comejv** [comment]
Sorry for the (long) delay, finished the job that had me working with nuttx and then forgot about it.

Tell me if the commit message should reflect that it is a breaking change more.

**Review by jerpelea — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by comejv** [comment]
The job Linux (arm64-01) fails with this output:

> ====================================================================================
> Configuration/Tool: qemu-armv8a/rpproxy
> 2026-01-20 09:18:25
> ------------------------------------------------------------------------------------
>   Cleaning...
> /github/workspace/sources/apps/Application.mk:238: target 'signest.c.github.workspace.sources.apps.testing.ostest.o' given more than once in the same rule
> /github/workspace/sources/apps/Application.mk:238: target 'signest.c.github.workspace.sources.apps.testing.ostest.o' given more than once in the same rule
>   Configuring...
>   Building NuttX...
> cu_main.c: In function 'sigint':
> Error: cu_main.c:128:33: error: 'siginfo' undeclared (first use in this function)
>   128 |   FAR struct cu_globals_s *cu = siginfo->si_user;
>       |                                 ^~~~~~~
> cu_main.c:128:33: note: each undeclared identifier is reported only once for each function it appears in
> make[2]: *** [/github/workspace/sources/apps/Application.mk:330: cu_main.c.github.workspace.sources.apps.system.cu.o] Error 1
> make[2]: Target 'all' not remade because of errors.
> make[1]: *** [Makefile:54: /github/workspace/sources/apps/system/cu_all] Error 2
> make[1]: Target 'all' not remade because of errors.
> make: *** [tools/LibTargets.mk:248: /github/workspace/sources/apps/libapps.a] Error 2
> make: Target 'all' not remade because of errors.
> /github/workspace/sources/nuttx/tools/testbuild.sh: line 385: /github/workspace/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
>   [1/1] Normalize qemu-armv8a/rpproxy

Is there something I'm supposed to do about that? At first glance it doesn't look related to my changes.

**Comment by xiaoxiang781216** [comment]
fixed here: https://github.com/apache/nuttx-apps/pull/3349

**Comment by xiaoxiang781216** [comment]
@comejv apps side need fix:
```
cap_main.c: In function 'cap_main':
Error: cap_main.c:354:23: error: 'CAPIOC_FREQUENCE' undeclared (first use in this function); did you mean 'CAPIOC_FREQUENCY'?
  354 |       ret = ioctl(fd, CAPIOC_FREQUENCE,
      |                       ^~~~~~~~~~~~~~~~
      |                       CAPIOC_FREQUENCY
```

**Comment by comejv** [comment]
How should I go about this? Because if I fix the usage first there will be failing tests in nuttx-app's CI because definition hasn't been fixed here right?

Or should I just create a PR for nuttx-apps with the new macro?

I opened PR https://github.com/apache/nuttx-apps/pull/3365

**Review by simbit18 — APPROVED** [review]
