### PR TITLE
arch/arm/stm32: fix undeclared page variable in flash write

### LINKED ISSUE #18172: [BUG] Compilation error in stm32f10xxf30xx_flash.c: 'page' variable used without definition
### Description / Steps to reproduce the issue

When compiling arch/arm/src/stm32/stm32f10xxf30xx_flash.c targets, there is a compilation error in stm32f10xxf30xx_flash.c file.

### On which OS does this issue occur?

[OS: Linux]

### What is the version of your OS?

Ubuntu-22.04

### NuttX Version

Release 11.0.0

### Issue Architecture

[Arch: arm]

### Issue Area

[Area: Board support]

### Host information

_No response_

### Verification

- [x] I have verified before submitting the report.

### PR DESCRIPTION
**Pull request by adwait-godbole**
This PR fixes a compilation error in stm32f10xxf30xx_flash.c where the variable page was used without being declared in up_progmem_write().

The issue is configuration-dependent and occurs when STM32_FLASH_DUAL_BANK is enabled.

The fix derives the page index from the write address using up_progmem_getpage() and uses it for flash bank selection.

Fixes #18172

### CODE REVIEW

**Review by xiaoxiang781216 — DISMISSED** [review]

**Comment by adwait-godbole** [comment]
@acassis please review. Thanks :).

**Review by acassis — DISMISSED** [review]

**Comment by acassis** [comment]
@adwait-godbole seems better now!

Hey @raiden00pl could you please take a look too?

File: arch/arm/src/stm32/stm32f10xxf30xx_flash.c [hunk 1]
```diff
@@ -296,6 +296,31 @@ ssize_t up_progmem_write(size_t addr, const void *buf, size_t count)
 #if defined(STM32_FLASH_DUAL_BANK)
   /* Handle paged FLASH */
 
+  size_t flash_offset;
+  size_t page;
+
+  /* Compute flash offset */
+
+  if (addr >= STM32_FLASH_BASE)
```
Comment (raiden00pl) [inline arch/arm/src/stm32/stm32f10xxf30xx_flash.c:305]: this is already done below, why duplicate code? 

```
  /* Check for valid address range */

  if (addr >= STM32_FLASH_BASE)
    {
      addr -= STM32_FLASH_BASE;
    }

  if ((addr + count) > STM32_FLASH_SIZE)
    {
      return -EFAULT;
    }

```

**Review by raiden00pl — CHANGES_REQUESTED** [review]
move https://github.com/apache/nuttx/blob/425a760799353f601c5c6e54b43d9ce390355465/arch/arm/src/stm32/stm32f10xxf30xx_flash.c#L309-L326 before https://github.com/apache/nuttx/blob/425a760799353f601c5c6e54b43d9ce390355465/arch/arm/src/stm32/stm32f10xxf30xx_flash.c#L296

**Review by raiden00pl — APPROVED** [review]

**Comment by acassis** [comment]
Thank you @adwait-godbole !!!
