### PR TITLE
sched/sched_roundrobin.c: fix round-robin scheduling in SMP mode

### LINKED ISSUE #17828: [BUG] esp32-devkitc:mcuboot_update_agent
### Description / Steps to reproduce the issue

Following the description, the update process starts but randomly hangs after a few percent of downloading. I confirmed that everything works as expected for nuttx-12.4.0, but not for the latest version nuttx-12.12.0.

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff7c98,len:6980
load:0x40078000,len:13428
load:0x40090000,len:8712
entry 0x4007b41c
[esp32] [INF] *** Booting MCUboot build v2.2.0-118-gaa4fa2b6 ***
[esp32] [INF] [boot] chip revision: v3.1
[esp32] [INF] [boot.esp32] SPI Speed      : 40MHz
[esp32] [INF] [boot.esp32] SPI Mode       : DIO
[esp32] [INF] [boot.esp32] SPI Flash Size : 4MB
[esp32] [INF] [boot] Enabling RNG early entropy source...
[esp32] [INF] Primary image: magic=good, swap_type=0x1, copy_done=0x3, image_ok=0x1
[esp32] [INF] Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
[esp32] [INF] Boot source: primary slot
[esp32] [INF] Image index: 0, Swap type: none
[esp32] [INF] Disabling RNG early entropy source...
[esp32] [INF] br_image_off = 0x20000
[esp32] [INF] ih_hdr_size = 0x20
[esp32] [INF] Loading image 0 - slot 0 from flash, area id: 1
[esp32] [INF] DRAM segment: start=0x384fc, size=0x3434, vaddr=0x3ffc22a0
[esp32] [INF] IRAM segment: start=0x20080, size=0x1847c, vaddr=0x40080000
[esp32] [INF] start=0x40085288
IROM segment aligned lma 0x00060000 vma 0x400d0000 len 0x079cb8 (498872)
DROM segment aligned lma 0x00040000 vma 0x3f410000 len 0x013628 (79400)
telnetd [8:100]

NuttShell (NSH) NuttX-12.12.0
This is MCUBoot Update Agent image
nsh> 
nsh> mcuboot_agent http://192.168.1.102:8000/nuttx.bin
MCUboot Update Agent example
Downloading from http://192.168.1.102:8000/nuttx.bin
Firmware Update size: 1048576 bytes
Received: 512      of 1048576 bytes [0%]
Received: 1024     of 1048576 bytes [0%]
Received: 1536     of 1048576 bytes [0%]
Received: 2048     of 1048576 bytes [0%]
Received: 2560     of 1048576 bytes [0%]
Received: 3072     of 1048576 bytes [0%]
Received: 3584     of 1048576 bytes [0%]
Received: 4096     of 1048576 bytes [0%]
Received: 4608     of 1048576 bytes [0%]
Received: 5120     of 1048576 bytes [0%]
Received: 5632     of 1048576 bytes [0%]
Received: 6144     of 1048576 bytes [0%]
Received: 6656     of 1048576 bytes [0%]
Received: 7168     of 1048576 bytes [0%]
Received: 7680     of 1048576 bytes [0%]
Received: 8192     of 1048576 bytes [0%]
Received: 8704     of 1048576 bytes [0%]
Received: 9216     of 1048576 bytes [0%]
Received: 9728     of 1048576 bytes [0%]
Received: 10240    of 1048576 bytes [0%]
Received: 10752    of 1048576 bytes [1%]
Received: 11264    of 1048576 bytes [1%]
Received: 11776    of 1048576 bytes [1%]
Received: 12288    of 1048576 bytes [1%]

```

### On which OS does this issue occur?

[OS: Linux]

### What is the version of your OS?

Debian12

### NuttX Version

12.12.0

### Issue Architecture

[Arch: xtensa]

### Issue Area

[Area: Applications]

### Host information

esptool v4.10.0

### Verification

- [x] I have verified before submitting the report.

### PR DESCRIPTION
**Pull request by fdcavalcanti**
- sched/sched_roundrobin.c: fix round-robin scheduling in SMP mode

In SMP mode, running tasks are in g_assignedtasks[cpu], not the ready-to-run list, so tcb->flink is NULL. When a round-robin timeslice expires, checking tcb->flink fails to find the next task.

Fix by calling nxsched_switch_running() directly in SMP mode when the timeslice expires, which properly finds the next eligible task from the ready-to-run list.

## Summary

This fixes #17828 and ESP32 `ostest` errors on `rr_test`.

In NuttX SMP, when a round-robin task’s timeslice expires, the code tried to find the next task by checking `tcb->flink` (the next task in the ready-to-run list). In SMP, running tasks are stored in `g_assignedtasks[cpu]`, not in the ready-to-run list, so `tcb->flink` is NULL. This prevented finding the next task and caused the round-robin test to fail.

### Fixing
Instead of checking `tcb->flink`, we call `nxsched_switch_running()` directly. This function:
- Looks in the ready-to-run list for the next eligible task
- Handles SMP-specific logic
- Returns true if a switch should occur

### Main changes
Before (broken):
```c
if (tcb->flink && tcb->flink->sched_priority >= tcb->sched_priority)
{
  // Switch to next task
}
```

This failed because `tcb->flink` was NULL in SMP mode.
After (fixed):

```c
else if (nxsched_switch_running(tcb->cpu, true))
{ 
  up_switch_context(this_task(), rtcb);
}
```
This directly uses the scheduler function that knows how to find the next task in SMP mode.

## Impact

Impact on user: Round-robin scheduling (SCHED_RR) works correctly in SMP mode. Applications using round-robin scheduling will now properly alternate between tasks of the same priority.

Impact on build: No.

Impact on hardware: Only affects SMP-capable hardware. No hardware changes required.

Impact on documentation: No.

Impact on security: No.

Impact on compatibility: No.

## Testing
`ostest` is passing on SMP ESP32 and ESP32S3.
Internal CI shows no errors regarding scheduler.
Fixes issues on network when SMP is enabled (getting stuck on downloads).

### CODE REVIEW

File: sched/sched/sched_roundrobin.c [hunk 1]
```diff
@@ -180,33 +180,36 @@ clock_t nxsched_process_roundrobin(FAR struct tcb_s *tcb, clock_t ticks,
            * give that task a shot.
            */
 
-          if (tcb->flink &&
-              tcb->flink->sched_priority >= tcb->sched_priority)
-            {
-              FAR struct tcb_s *rtcb = this_task();
+          FAR struct tcb_s *rtcb = this_task();
```
Comment (acassis) [inline sched/sched/sched_roundrobin.c:183]: @fdcavalcanti probably this comment above needs to be update to the new way to switch to the next task

Comment (fdcavalcanti) [reply sched/sched/sched_roundrobin.c:183]: Thanks! Just  changed.
