### PR TITLE
fix missing gnu-elf.ld cp when generating export

### LINKED ISSUE #16973: [BUG] Non-blocking make export error: missing gnu-elf.ld
### Description / Steps to reproduce the issue

When I configure for `stm32f4discovery:nsh` and then run `make export`, I get a warning about a missing linker script:
```
cp: cannot stat '/home/thomas/nuttxspace/nuttx/libs/libc/elf/gnu-elf.ld': No such file or directory
```

Despite this, the export archive is created successfully and the build is not blocked. It seems the export step is trying to copy a file that doesn’t exist anymore.

### Steps to Reproduce:

1. Configure NuttX:
```
./tools/configure.sh -l stm32f4discovery:nsh
```
2. Run export:
```
make export
```

**Output**:
```
Create version.h
LN: platform/board to /home/thomas/nuttxspace/apps/platform/dummy
Register: hello
Register: dd
Register: nsh
Register: sh
CC:  chip/stm32_gpio.c chip/stm32_gpio.c:44:11: note: '#pragma message: CONFIG_STM32_USE_LEGACY_PINMAP will be deprecated migrate board.h see tools/stm32_pinmap_tool.py'
   44 | #  pragma message "CONFIG_STM32_USE_LEGACY_PINMAP will be deprecated migrate board.h see tools/stm32_pinmap_tool.py"
      |           ^~~~~~~
CC:  chip/stm32_flash.c In file included from chip/stm32_flash.c:40:
chip/stm32f20xxf40xx_flash.c:53:4: warning: #warning "Default Flash Configuration Used - See Override Flash Size Designator" [-Wcpp]
   53 | #  warning "Default Flash Configuration Used - See Override Flash Size Designator"
      |    ^~~~~~~
cp: cannot stat '/home/thomas/nuttxspace/nuttx/libs/libc/elf/gnu-elf.ld': No such file or directory
```

*Notes*:
The error is non-blocking and does not prevent the export archive from being created. I just wanted to check if this is an intentional leftover or something that should be cleaned up. I’d be happy to look into it further if needed.

### On which OS does this issue occur?

[OS: Linux]

### What is the version of your OS?

Ubuntu 24.04

### NuttX Version

master

### Issue Architecture

[Arch: arm]

### Issue Area

[Area: Configuring]

### Host information

_No response_

### Verification

- [x] I have verified before submitting the report.

### PR DESCRIPTION
**Pull request by trns1997**
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*

Closes #16973

## Summary
`make export` currently fails with the warning:
```
cp: cannot stat '.../libs/libc/elf/gnu-elf.ld': No such file or directory
```
This happens because the file `gnu-elf.ld` was removed and replaced with `gnu-elf.ld.in`. The real `gnu-elf.ld` is now only generated when `CONFIG_LIBC_MODLIB=y` (via modlib).

However, `tools/mkexport.sh` still assumes that `gnu-elf.ld` always exists and tries to copy it unconditionally, leading to the error.

## Impact

- Removes the confusing “cannot stat gnu-elf.ld” error during make export.
- No functional change for users who have `CONFIG_LIBC_MODLIB=y` (the generated gnu-elf.ld is still copied).
- For users without CONFIG_LIBC_MODLIB, the .in template is exported in place of the missing file, ensuring the export step succeeds without error.

No impact on runtime behavior, build outputs, or compatibility.

## Testing
- Host: Ubuntu 22.04, gcc 11.4.0.
- Target: stm32f4discovery:nsh.

- [x] Export no error with `CONFIG_LIBC_MODLIB=n`
- [ ] Export no error with `CONFIG_LIBC_MODLIB=y`

### CODE REVIEW

**Comment by trns1997** [comment]
ping @acassis @leducp

File: tools/mkexport.sh [hunk 1]
```diff
@@ -185,10 +187,15 @@ cp "${TOPDIR}/tools/incdir.c" "${EXPORTDIR}/tools/."
...
+APPLDIN=gnu-elf.ld.in
+
 if [ -f "${BOARDDIR}/scripts/${APPLD}" ]; then
   cp -f "${BOARDDIR}/scripts/${APPLD}" "${EXPORTDIR}/scripts/."
-else
+elif [ -f "${TOPDIR}/libs/libc/elf/${APPLD}" ]; then
   cp -f "${TOPDIR}/libs/libc/elf/${APPLD}" "${EXPORTDIR}/scripts/."
+elif [ -f "${TOPDIR}/libs/libc/elf/${APPLDIN}" ]; then
+  # Fall back to exporting the template if the real file is missing
+  cp -f "${TOPDIR}/libs/libc/elf/${APPLDIN}" "${EXPORTDIR}/scripts/${APPLD}"
```
Comment (acassis) [inline tools/mkexport.sh]: I think this part shouldn't be included, because if the file doesn't exist is because LIBC_MODLIB is not enabled, then this file cannot be used by applications anyway

**Comment by anchao** [comment]
@trns1997 @acassis Thanks for your detailed analysis!

`CONFIG_LIBC_MODLIB` has been deprecated in commit https://github.com/apache/nuttx/pull/15765 and is now named
`CONFIG_LIBC_MODLIB` -> `CONFIG_LIBC_ELF`

On current architectures, `gnu-elf.ld.in` requires compiler preprocessing before use, so it cannot be simply copied:
https://github.com/apache/nuttx/blob/master/libs/libc/elf/Makefile#L25-L28

I have 2 suggestions for fixing this issue:
1. Remove the check for CONFIG_LIBC_ELF and always generate gnu-elf.ld:
image

```
diff --git a/libs/libc/Makefile b/libs/libc/Makefile
index 33bcba86d0..00c2a4f8df 100644
--- a/libs/libc/Makefile
+++ b/libs/libc/Makefile
@@ -183,9 +183,7 @@ context:: bin kbin
 ifeq ($(CONFIG_LIBC_ZONEINFO_ROMFS),y)
        $(Q) $(MAKE) -C zoneinfo context BIN=$(BIN)
 endif
-ifeq ($(CONFIG_LIBC_ELF),y)
        $(Q) $(MAKE) -C elf context
-endif
 
 
 # Dependencies

```
2. Add a check in mkexport.sh to only copy gnu-elf.ld if CONFIG_LIBC_ELF is enabled:

image


```
diff --git a/tools/mkexport.sh b/tools/mkexport.sh
index 9d8c42d9c6..7346716f75 100755
--- a/tools/mkexport.sh
+++ b/tools/mkexport.sh
@@ -123,6 +123,10 @@ if [ ! -z "${CONFIG_VERSION_STRING}" -a "${CONFIG_VERSION_STRING}" != "0.0" ]; t
   VERSION="-${CONFIG_VERSION_STRING}"
 fi
 
+# Get the config string
+
+source "${TOPDIR}/.config"
+
 # Create the export directory
 
 EXPORTSUBDIR="nuttx-export${VERSION}"
@@ -184,15 +188,19 @@ cp "${TOPDIR}/tools/incdir.c" "${EXPORTDIR}/tools/."
 
 # Copy the board specific linker if found, or use the default when not.
 
-APPLD=gnu-elf.ld
-if [ -f "${BOARDDIR}/scripts/${APPLD}" ]; then
-  cp -f "${BOARDDIR}/scripts/${APPLD}" "${EXPORTDIR}/scripts/."
-else
-  cp -f "${TOPDIR}/libs/libc/elf/${APPLD}" "${EXPORTDIR}/scripts/."
-fi
+if [ ! -z "${CONFIG_LIBC_ELF}" ]; then
+  APPLD=gnu-elf.ld
+  if [ -f "${BOARDDIR}/scripts/${APPLD}" ]; then
+    cp -f "${BOARDDIR}/scripts/${APPLD}" "${EXPORTDIR}/scripts/."
+  else
+    cp -f "${TOPDIR}/libs/libc/elf/${APPLD}" "${EXPORTDIR}/scripts/."
+  fi
 
-if [ "${NUTTX_BUILD}" = "kernel" ]; then
-  LDNAME=${APPLD}
+  if [ "${NUTTX_BUILD}" = "kernel" ]; then
+    LDNAME=${APPLD}
+  fi
+else
+  LDNAME=""
 fi
 
 # Copy the board config script

```

I prefer option 2  : )  . If you agree with either solution, please update the current PR.

**Comment by trns1997** [comment]
@anchao i prefere option 2 as well but doesn't this already do the trick:
```
APPLD=gnu-elf.ld

if [ -f "${BOARDDIR}/scripts/${APPLD}" ]; then
  cp -f "${BOARDDIR}/scripts/${APPLD}" "${EXPORTDIR}/scripts/."
elif [ -f "${TOPDIR}/libs/libc/elf/${APPLD}" ]; then
  cp -f "${TOPDIR}/libs/libc/elf/${APPLD}" "${EXPORTDIR}/scripts/."
fi
```

But maybe for clarity sake its better to check for the `CONFIG_LIBC_ELF` var.

**Comment by trns1997** [comment]
When running:
```
./tools/configure.sh -E -l stm32f4discovery:nsh && make export -j8
```
with set -e enabled, the build stops with:
```
make: *** [tools/Unix.mk:781: export] Error 1
```
Verbose output shows the actual failure:
```
if [ -d "/home/thomas/nuttxspace/nuttx/nuttx-export-12.10.0/startup" ]; then \
  cp -f crt0.o "/home/thomas/nuttxspace/nuttx/nuttx-export-12.10.0/startup/."; \
else \
  echo "/home/thomas/nuttxspace/nuttx/nuttx-export-12.10.0/startup does not exist"; \
  exit 1; \
fi
```
it’s because the startup/ directory inside the export tree is never created, and the script exits when it tries to copy crt0.o there.

This looks to be the same root cause seen here in https://github.com/apache/nuttx/pull/16970#issuecomment-3254893411 . Hopefully solving this will resolve both problems :)

**Comment by leducp** [comment]
What about adding a CI test linking a C++ helloworld with CMake to avoid regression in the future? (At least from a compile POV).

**Comment by trns1997** [comment]
> What about adding a CI test linking a C++ helloworld with CMake to avoid regression in the future? (At least from a compile POV).

Totally agree, lets fix up all this get it functional, update the doc and then lets add a basic out of tree build test

**Comment by trns1997** [comment]
@leducp was right in comment: https://github.com/apache/nuttx/pull/16970#issuecomment-3257700071. This commit is caused the issue. The commit moved/centralized `crt0.c` from arch/* into arch/common and builds crt0.o as part of libarch.a. That means `__start` is now provided both by board startup code (e.g. stm32_start.o in libarch.a) and by the exported crt0.o in startup/, which leads to a "multiple definition of __start" error when building apps against an export package. Updating the line 22 in `scripts/toolchain.cmake` from `file(GLOB STARTUP_OBJS ${NUTTX_PATH}/startup/*)` to `set(STARTUP_OBJ ${NUTTX_PATH}/startup/crt0.o)` forces the app to use `crt0.o`. I have the app that build in https://github.com/apache/nuttx/pull/16970 but not sure this is the correct expected solution. I would like someones input on this before i implement this fix.

**Comment by trns1997** [comment]
> @leducp was right in comment: [#16970 (comment)](https://github.com/apache/nuttx/pull/16970#issuecomment-3257700071). This commit is caused the issue. The commit moved/centralized `crt0.c` from arch/* into arch/common and builds crt0.o as part of libarch.a. That means `__start` is now provided both by board startup code (e.g. stm32_start.o in libarch.a) and by the exported crt0.o in startup/, which leads to a "multiple definition of __start" error when building apps against an export package. Updating the line 22 in `scripts/toolchain.cmake` from `file(GLOB STARTUP_OBJS ${NUTTX_PATH}/startup/*)` to `set(STARTUP_OBJ ${NUTTX_PATH}/startup/crt0.o)` forces the app to use `crt0.o`. I have the app that build in #16970 but not sure this is the correct expected solution. I would like someones input on this before i implement this fix.

@xiaoxiang781216 could we get your input on this?

**Comment by xiaoxiang781216** [comment]
@anjiahao1 please take a look.

File: tools/mkexport.sh [hunk 2]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
-# those directories into the EXPORTDIR
+# Some architectures keep all headers in src/, some only a few, and others none.
+
+if [ -d "${ARCHDIR}" ]; then
+    # Expand the glob safely
+    set -- "${ARCHDIR}"/*.h
+    if [ -e "$1" ]; then
+        echo "Copying architecture headers from ${ARCHDIR} to ${EXPORTDIR}/arch"
+        if ! cp -f "$@" "${EXPORTDIR}/arch/"; then
+            echo "Error: Failed to copy headers from ${ARCHDIR}" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 3]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+            exit 1
+        fi
+    else
+        echo "Notice: No header files found in ${ARCHDIR}" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 4]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+    fi
+else
+    echo "Warning: Architecture directory ${ARCHDIR} does not exist" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 5]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
   ARCH_HDRDIRS="arm armv7-m avr avr32 board common chip mips32"
+
   for hdir in $ARCH_HDRDIRS; do
+    srcdir="${ARCHDIR}/${hdir}"
+    dstdir="${EXPORTDIR}/arch/${hdir}"
 
     # Does the directory (or symbolic link) exist?
+    if [ -d "$srcdir" ] || [ -h "$srcdir" ]; then
+      mkdir -p "$dstdir" || {
+        echo "Error: mkdir $dstdir failed" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 6]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+        exit 1
+      }
+
+      # Copy headers if they exist
+      set -- "$srcdir"/*.h
+      if [ -e "$1" ]; then
+        echo "Copying headers from $srcdir to $dstdir"
+        if ! cp -f "$@" "$dstdir/"; then
+          echo "Error: Failed to copy headers from $srcdir" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 7]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+    if [ -d "$srcdir" ] || [ -h "$srcdir" ]; then
+      mkdir -p "$dstdir" || {
+        echo "Error: mkdir $dstdir failed" >&2
+        exit 1
+      }
+
+      # Copy headers if they exist
+      set -- "$srcdir"/*.h
+      if [ -e "$1" ]; then
+        echo "Copying headers from $srcdir to $dstdir"
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 8]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+        if ! cp -f "$@" "$dstdir/"; then
+          echo "Error: Failed to copy headers from $srcdir" >&2
+          exit 1
+        fi
+      else
+        echo "Notice: No header files found in $srcdir" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 9]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
-        mkdir "${EXPORTDIR}/arch/${hdir}/hardware" || \
-          { echo "MK: 'mkdir ${EXPORTDIR}/arch/${hdir}/hardware' failed"; exit 1; }
-
-        # Then copy the header files (only) into the new directory
-
-        cp -f "${ARCHDIR}"/${hdir}/hardware/*.h "${EXPORTDIR}"/arch/${hdir}/hardware/. 2>/dev/null
+      # Handle hardware subdir if it exists
+      if [ -d "$srcdir/hardware" ]; then
+        mkdir -p "$dstdir/hardware" || {
+          echo "Error: mkdir $dstdir/hardware failed" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 10]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+          exit 1
+        }
+
+        set -- "$srcdir/hardware"/*.h
+        if [ -e "$1" ]; then
+          echo "Copying headers from $srcdir/hardware to $dstdir/hardware"
+          if ! cp -f "$@" "$dstdir/hardware/"; then
+            echo "Error: Failed to copy headers from $srcdir/hardware" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 11]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+      # Handle hardware subdir if it exists
+      if [ -d "$srcdir/hardware" ]; then
+        mkdir -p "$dstdir/hardware" || {
+          echo "Error: mkdir $dstdir/hardware failed" >&2
+          exit 1
+        }
+
+        set -- "$srcdir/hardware"/*.h
+        if [ -e "$1" ]; then
+          echo "Copying headers from $srcdir/hardware to $dstdir/hardware"
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 12]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+          if ! cp -f "$@" "$dstdir/hardware/"; then
+            echo "Error: Failed to copy headers from $srcdir/hardware" >&2
+            exit 1
+          fi
+        else
+          echo "Notice: No hardware headers in $srcdir/hardware" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 13]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
   done
 
-  # Copy OS internal header files as well.  They are used by some architecture-
-  # specific header files.
-
-  mkdir "${EXPORTDIR}/arch/os" || \
-    { echo "MK: 'mkdir ${EXPORTDIR}/arch/os' failed"; exit 1; }
+  # Copy OS internal header files
+  mkdir -p "${EXPORTDIR}/arch/os" || {
+    echo "Error: mkdir ${EXPORTDIR}/arch/os failed" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 14]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
-    mkdir "${EXPORTDIR}/arch/os/${dir}" || \
-      { echo "MK: 'mkdir ${EXPORTDIR}/arch/os/${dir}' failed"; exit 1; }
-    cp -f "${TOPDIR}"/sched/${dir}/*.h "${EXPORTDIR}"/arch/os/${dir}/. 2>/dev/null
-  done
+    srcdir="${TOPDIR}/sched/${dir}"
+    dstdir="${EXPORTDIR}/arch/os/${dir}"
 
-  # Add the board library to the list of libraries
+    mkdir -p "$dstdir" || {
+      echo "Error: mkdir $dstdir failed" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 15]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+      exit 1
+    }
+
+    set -- "$srcdir"/*.h
+    if [ -e "$1" ]; then
+      echo "Copying OS headers from $srcdir to $dstdir"
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 16]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+      if ! cp -f "$@" "$dstdir/"; then
+        echo "Error: Failed to copy headers from $srcdir" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

File: tools/mkexport.sh [hunk 17]
```diff
@@ -364,70 +367,101 @@ cp -LR -p "${TOPDIR}/include" "${EXPORTDIR}/." || \
...
+        exit 1
+      fi
+    else
+      echo "Notice: No headers in $srcdir" >&2
```
Comment (trns1997) [inline tools/mkexport.sh]: add `MK:` to output message

**Comment by trns1997** [comment]
> When running:
> 
> ```
> ./tools/configure.sh -E -l stm32f4discovery:nsh && make export -j8
> ```
> 
> with set -e enabled, the build stops with:
> 
> ```
> make: *** [tools/Unix.mk:781: export] Error 1
> ```
> 
> Verbose output shows the actual failure:
> 
> ```
> if [ -d "/home/thomas/nuttxspace/nuttx/nuttx-export-12.10.0/startup" ]; then \
>   cp -f crt0.o "/home/thomas/nuttxspace/nuttx/nuttx-export-12.10.0/startup/."; \
> else \
>   echo "/home/thomas/nuttxspace/nuttx/nuttx-export-12.10.0/startup does not exist"; \
>   exit 1; \
> fi
> ```
> 
> it’s because the startup/ directory inside the export tree is never created, and the script exits when it tries to copy crt0.o there.
> 
> This looks to be the same root cause seen here in [#16970 (comment)](https://github.com/apache/nuttx/pull/16970#issuecomment-3254893411) . Hopefully solving this will resolve both problems :)

This wasn’t the actual root cause. The real issue was the use of `2>/dev/null`, which was hiding the underlying error. I’ve updated the script to replace `2>/dev/null` with checks, allowing us to use `set -e`. This ensures that any errors are caught immediately and helps prevent regressions in `mkexport.sh`. The next step will be to add an out-of-tree build test in CI to verify that the exported content continues to work over time.

**Comment by leducp** [comment]
Good work!
