### PR TITLE
drivers/sensors/ms56xx: Use nxsig_usleep for long delays.

### LINKED ISSUE #15826: [BUG] Floating point issues on STM32H743
### Description / Steps to reproduce the issue

I am encountering numerous strange issues on the STM32H743.

Floating point numbers seem to not work for the MS56xx driver, used on an MS5607.

```console
Mointor objects num:1
object_name:sensor_baro, object_instance:0
sensor_baro(now:18990000):timestamp:18990000,pressure:42948200.000000,temperature:21.870001
sensor_baro(now:19030000):timestamp:19030000,pressure:42948204.000000,temperature:21.809999
sensor_baro(now:19070000):timestamp:19070000,pressure:42948204.000000,temperature:21.760000
sensor_baro(now:19110000):timestamp:19110000,pressure:42948204.000000,temperature:21.760000
sensor_baro(now:19150000):timestamp:19150000,pressure:42948204.000000,temperature:21.760000
sensor_baro(now:19190000):timestamp:19190000,pressure:42948204.000000,temperature:21.879999
sensor_baro(now:19230000):timestamp:19230000,pressure:42948204.000000,temperature:21.700001
sensor_baro(now:19270000):timestamp:19270000,pressure:42948204.000000,temperature:21.750000
sensor_baro(now:19310000):timestamp:19310000,pressure:42948204.000000,temperature:21.700001
sensor_baro(now:19350000):timestamp:19350000,pressure:42948204.000000,temperature:21.809999
Object name:sensor_baro0, recieved:10
Total number of received Message:10/10
```

I am also seeing strange floating point numbers on the LIS2MDL driver and LSM6DSO32 driver. Additionally, when running `uorb_listener`, the kernel panics if I try to read from the LSM6DSO32. I had an earlier kernel panic with `ps` which I resolved by increasing stack sizes as recommended in this issue: https://github.com/apache/nuttx/issues/11463

I also cannot seem to get any information about the panic. I've enabled core dumps, scheduler and sensor error output, etc. without luck. If there are any suggestions on what I can enable or try to debug this and provide more information, please let me know. These drivers work without issue on RP2040 based boards, so I am not sure what could be the issue.

I have tried with the FPU enabled and disabled with the same results. I've increased every stack size option I could find to 4096 bytes without success.

This is the output seen before the kernel crashes:
```console
nsh> uorb_listener -n 10 sensor_accel0

Mointor objects num:1
object_name:sensor_accel, object_instance:0
lsm6dso32_activate: About to lock
lsm6dso32_activate: locked
lsm6dso32_activate: About to set odr
lsm6dso32_activate: odr set
lsm6dso32_activate: Waking up LSM6DSO32 polling thread
lsm6dso32_activate: LSM6DSO32 activated
Waited for 5 seconds withou
```
Then the output is cut off and the kernel panic status LED is activated. Some times the LED is held static, other times it blinks at 1Hz (for the same `uorb_listener` command).

### On which OS does this issue occur?

[OS: Linux]

### What is the version of your OS?

Arch Linux

### NuttX Version

master

### Issue Architecture

[Arch: arm]

### Issue Area

[Area: Drivers]

### Host information

_No response_

### Verification

- [x] I have verified before submitting the report.

### PR DESCRIPTION
**Pull request by linguini1**
## Summary

Longer delays (10ms) are performed with `nxsig_usleep()` instead of `up_udelay()`.

## Impact

The waiting process in this driver is now more efficient since it does not rely on busy waiting using a loop for its longer delays.

## Testing

Testing was performed on a custom STM32H743 flight computer where an issue was first observed with incorrect pressure readings because of an incorrect `CONFIG_BOARD_LOOPSPERMSEC` value. This closes #15826.

With the new changes, pressure is read correctly:

```console
NuttShell (NSH) NuttX-12.8.0
nsh> uorb_listener -r 50 -n 10 sensor_baro0

Mointor objects num:1
object_name:sensor_baro, object_instance:0
sensor_baro(now:7900000):timestamp:7900000,pressure:1003.309998,temperature:21.230000
sensor_baro(now:7970000):timestamp:7970000,pressure:1003.309998,temperature:21.280001
sensor_baro(now:8040000):timestamp:8040000,pressure:1003.330017,temperature:21.309999
sensor_baro(now:8110000):timestamp:8110000,pressure:1003.309998,temperature:21.340000
sensor_baro(now:8180000):timestamp:8180000,pressure:1003.340027,temperature:21.360001
sensor_baro(now:8250000):timestamp:8250000,pressure:1003.320007,temperature:21.370001
sensor_baro(now:8320000):timestamp:8320000,pressure:1003.340027,temperature:21.389999
sensor_baro(now:8390000):timestamp:8390000,pressure:1003.349976,temperature:21.400000
sensor_baro(now:8460000):timestamp:8460000,pressure:1003.349976,temperature:21.410000
sensor_baro(now:8530000):timestamp:8530000,pressure:1003.330017,temperature:21.420000
Object name:sensor_baro0, recieved:10
Total number of received Message:10/10
```

### CODE REVIEW

File: drivers/sensors/ms56xx_uorb.c [hunk 1]
```diff
@@ -286,7 +286,7 @@ static inline void baro_measure_read(FAR struct ms56xx_dev_s *priv,
 
   /* Wait data acquisition */
 
-  up_udelay(10000);
+  nxsig_usleep(10000);
```
Comment (anchao) [inline drivers/sensors/ms56xx_uorb.c:289]: Why not replace all up_udelays() to nxsig_usleep()(? I think this will be more efficient in CPU utilization.

**Review by anchao — APPROVED** [review]

**Review by acassis — APPROVED** [review]
